### ISSUE TITLE
Error 502: Bad Gateway trying to access web frontend

### ISSUE THREAD

**Issue by CharlesJQuarra** [million12/docker-gitbucket#9]
I am getting a 502 Bad Gateway error trying to access gitbucket. This is the log output

```
Nginx status page: allowed address set to 127.0.0.1.
[LOG 16:47:26] Creating Cache directory for nginx
[LOG 16:47:26] Starting GitBucket
2017-11-29 16:47:26,275 CRIT Supervisor running as root (no user in config file)
2017-11-29 16:47:26,275 INFO Included extra file "/etc/supervisor.d/gitbucket.conf" during parsing
2017-11-29 16:47:26,275 INFO Included extra file "/etc/supervisor.d/nginx.conf" during parsing
2017-11-29 16:47:26,280 INFO RPC interface 'supervisor' initialized
2017-11-29 16:47:26,281 INFO supervisord started with pid 31
2017-11-29 16:47:27,284 INFO spawned: 'nginx' with pid 34
2017-11-29 16:47:27,286 INFO spawned: 'nginx-reload' with pid 35
2017-11-29 16:47:27,289 INFO spawned: 'gitbucket' with pid 36
2017-11-29 16:47:27,293 DEBG 'nginx' stderr output:
2017/11/29 16:47:27 [notice] 34#34: using the "epoll" event method
2017/11/29 16:47:27 [notice] 34#34: nginx/1.11.9
2017/11/29 16:47:27 [notice] 34#34: built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
2017/11/29 16:47:27 [notice] 34#34: OS: Linux 4.10.0-40-generic
2017/11/29 16:47:27 [notice] 34#34: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2017/11/29 16:47:27 [notice] 34#34: start worker processes

2017-11-29 16:47:27,294 DEBG 'nginx' stderr output:
2017/11/29 16:47:27 [notice] 34#34: start worker process 47
2017/11/29 16:47:27 [notice] 34#34: start worker process 48

2017-11-29 16:47:27,294 DEBG 'nginx' stderr output:
2017/11/29 16:47:27 [notice] 34#34: start worker process 49

2017-11-29 16:47:27,294 DEBG 'nginx' stderr output:
2017/11/29 16:47:27 [notice] 34#34: start worker process 50
2017/11/29 16:47:27 [notice] 34#34: start worker process 51
2017/11/29 16:47:27 [notice] 34#34: start worker process 52
2017/11/29 16:47:27 [notice] 34#34: start worker process 53
2017/11/29 16:47:27 [notice] 34#34: start worker process 54
2017/11/29 16:47:27 [notice] 34#34: start cache manager process 55
2017/11/29 16:47:27 [notice] 34#34: start cache loader process 56

2017-11-29 16:47:27,761 DEBG 'gitbucket' stderr output:
2017-11-29 16:47:27.760:INFO::main: Logging initialized @466ms

2017-11-29 16:47:27,833 DEBG 'gitbucket' stderr output:
2017-11-29 16:47:27.833:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT

2017-11-29 16:47:28,445 DEBG 'gitbucket' stderr output:
2017-11-29 16:47:28.444:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet

2017-11-29 16:47:28,445 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-11-29 16:47:28,445 INFO success: nginx-reload entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-11-29 16:47:28,445 INFO success: gitbucket entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-11-29 16:47:29,075 DEBG 'gitbucket' stdout output:
16:47:29.074 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...

2017-11-29 16:47:29,196 DEBG 'gitbucket' stdout output:
16:47:29.196 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.

2017-11-29 16:47:29,204 DEBG 'gitbucket' stdout output:
16:47:29.204 [main] INFO  g.core.servlet.InitializeListener - Check version
16:47:29.204 [main] INFO  g.core.servlet.InitializeListener - Start schema update

2017-11-29 16:47:29,477 DEBG 'gitbucket' stdout output:
16:47:29.477 [main] INFO  g.core.servlet.InitializeListener - Extract bundled plugins

2017-11-29 16:47:29,669 DEBG 'gitbucket' stdout output:
16:47:29.669 [main] INFO  g.core.servlet.InitializeListener - Initialize plugins

2017-11-29 16:47:29,685 DEBG 'gitbucket' stdout output:
16:47:29.685 [main] INFO  gitbucket.core.plugin.PluginRegistry - Initialize gitbucket-notifications-plugin_2.12-1.2.0.jar

2017-11-29 16:47:29,772 DEBG 'gitbucket' stdout output:
16:47:29.772 [Thread-12] INFO  g.core.plugin.PluginWatchThread - Start PluginWatchThread: /gitbucket-data/plugins

2017-11-29 16:47:29,793 DEBG 'gitbucket' stdout output:
16:47:29.793 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
16:47:29.793 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.3 created.

2017-11-29 16:47:29,795 DEBG 'gitbucket' stdout output:
16:47:29.794 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.

2017-11-29 16:47:29,795 DEBG 'gitbucket' stdout output:
16:47:29.795 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'QuartzScheduler~job' with instanceId 'job'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.


2017-11-29 16:47:29,795 DEBG 'gitbucket' stdout output:
16:47:29.795 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler 'QuartzScheduler~job
16:47:29.795 [main] INFO  o.quartz.impl.DirectSchedulerFactory - Quartz scheduler version: 2.2.3

2017-11-29 16:47:29,796 DEBG 'gitbucket' stdout output:
16:47:29.796 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler QuartzScheduler~job_$_job started.

2017-11-29 16:47:29,803 DEBG 'gitbucket' stdout output:
[INFO] [11/29/2017 16:47:29.801] [main] [[QuartzScheduler~job]] Setting up scheduled job 'Daily', with 'com.typesafe.akka.extension.quartz.QuartzCronSchedule@41ffaeb8'

2017-11-29 16:47:29,809 DEBG 'gitbucket' stdout output:
16:47:29.809 [main] INFO  o.scalatra.servlet.ScalatraListener - The cycle class name from the config: ScalatraBootstrap

2017-11-29 16:47:29,811 DEBG 'gitbucket' stdout output:
16:47:29.811 [main] INFO  o.scalatra.servlet.ScalatraListener - Initializing life cycle class: ScalatraBootstrap

2017-11-29 16:47:30,030 DEBG 'gitbucket' stderr output:
2017-11-29 16:47:30.030:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@4b6e1c0{/,file:///gitbucket-data/tmp/webapp/,AVAILABLE}{file:/opt/gitbucket.war}

2017-11-29 16:47:30,033 DEBG 'gitbucket' stderr output:
Exception in thread "main" 
2017-11-29 16:47:30,033 DEBG 'gitbucket' stderr output:
java.net.SocketException: Unresolved address
        at sun.nio.ch.Net.translateToSocketException(Net.java:131)
        at sun.nio.ch.Net.translateException(Net.java:157)

2017-11-29 16:47:30,033 DEBG 'gitbucket' stderr output:
        at sun.nio.ch.Net.translateException(Net.java:163)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:76)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:317)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at JettyLauncher.main(JettyLauncher.java:127)

2017-11-29 16:47:30,033 DEBG 'gitbucket' stderr output:
Caused by: java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:218)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        ... 7 more

2017-11-29 16:47:51,352 DEBG 'nginx' stderr output:
2017/11/29 16:47:51 [error] 47#47: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.148, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "gitbucket.intranet.local"
2017/11/29 16:47:51 [warn] 47#47: *1 upstream server temporarily disabled while connecting to upstream, client: 192.168.1.148, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "gitbucket.intranet.local"
2017/11/29 16:47:51 [error] 47#47: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.148, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "gitbucket.intranet.local"

2017-11-29 16:47:51,353 DEBG 'nginx' stderr output:
2017/11/29 16:47:51 [warn] 47#47: *1 upstream server temporarily disabled while connecting to upstream, client: 192.168.1.148, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "gitbucket.intranet.local"

2017-11-29 16:47:51,373 DEBG 'nginx' stderr output:
2017/11/29 16:47:51 [error] 47#47: *1 no live upstreams while connecting to upstream, client: 192.168.1.148, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "gitbucket.intranet.local"

2017-11-29 16:48:27,301 DEBG 'nginx' stderr output:
2017/11/29 16:48:27 [notice] 56#56: http file cache: /var/lib/nginx/cache 0.000M, bsize: 4096

2017-11-29 16:48:27,336 DEBG 'nginx' stderr output:
2017/11/29 16:48:27 [notice] 34#34: signal 17 (SIGCHLD) received
2017/11/29 16:48:27 [notice] 34#34: cache loader process 56 exited with code 0

2017-11-29 16:48:27,337 DEBG 'nginx' stderr output:
2017/11/29 16:48:27 [notice] 34#34: signal 29 (SIGIO) received

2017-11-29 16:59:24,352 DEBG 'nginx' stderr output:
2017/11/29 16:59:24 [error] 54#54: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "172.17.0.2"
2017/11/29 16:59:24 [warn] 54#54: *4 upstream server temporarily disabled while connecting to upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "172.17.0.2"
2017/11/29 16:59:24 [error] 54#54: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "172.17.0.2"
2017/11/29 16:59:24 [warn] 54#54: *4 upstream server temporarily disabled while connecting to upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "172.17.0.2"

2017-11-29 16:59:24,371 DEBG 'nginx' stderr output:
2017/11/29 16:59:24 [error] 54#54: *4 no live upstreams while connecting to upstream, client: 172.17.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "172.17.0.2"
```

bitbucket was started like this:

`docker run   -d   --name gitbucket   -p 80:80   -p 1443:443   -p 29418:29418   -e HOSTNAME=gitbucket.intranet.local   -e DATA_DIR=/gitbucket-data   -v /var/gitbucket:/gitbucket-data   million12/gitbucket`

No idea what could be the issue here

**Comment by pozgo** [comment]
Hi, 
Is it happening every time you start the image?
What are the permissions on your host OS on `/var/gitbucket` ?

Can you post `docker info` output please? 

Edited ----

There is an issue with 502. Im debugging it now.

**Comment by pozgo** [comment]
An Update on the issue... 

---

I'm going to strip this image to Alpine only. All heavy lifting should be done by either separate Nginx or HAProxy service. This image should stay as gitbucket only. 

I will soon release a new version with Alpine only. Your problem should be resolved then

**Comment by pozgo** [comment]
Refactored. New image is based on Alpine linux and started same way as before using supervisor. It should work ok now.
